name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_php-create-version-branch.yml@9a50807409916719ee5af7a9061bd4ddedc8bc03
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root Packages", "command": "root-outdated-check-major-release"},
          {"name": "Rector",        "command": "rector-outdated-check-major-release"}
        ]
